version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: prototipo_panaderia_ds-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: prototipo_panaderia_ds-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app

